const actionTypes = {
  VALIDATING_AUTHENTICATION: "VALIDATING_AUTHENTICATION",
  VALID_AUTHENTICATION: "VALID_AUTHENTICATION",
  INVALID_AUTHENTICATION: "INVALID_AUTHENTICATION",
};

export default actionTypes;
